### ISSUE TITLE
Improve footer logo quality

### ISSUE THREAD

**Issue by AntoineKM** [NationalSecurityAgency/nationalsecurityagency.github.io#47]
The footer logo is not in png or svg it's a pity because we have big borders not very pretty visually

**Comment by AntoineKM** [comment]
We are definitely not going to use an image that is publicly editable on a third party site.

_Originally posted by @ctubbsii in https://github.com/NationalSecurityAgency/nationalsecurityagency.github.io/pull/48#pullrequestreview-1326350807_

Okay, but I have searched on the NSA website for the official logo, I can't find it, could you please guide me in my search!

**Comment by ctubbsii** [comment]
> We are definitely not going to use an image that is publicly editable on a third party site.
> 
> _Originally posted by @ctubbsii in [#48 (review)](https://github.com/NationalSecurityAgency/nationalsecurityagency.github.io/pull/48#pullrequestreview-1326350807)_
> 
> Okay, but I have searched on the NSA website for the official logo, I can't find it, could you please guide me in my search!

I would have to do some homework to find something myself. These images are protected by trademark, and need to be used with permission, so we have to ensure we're getting them from an authorized source. Is the main concern the background of the seal not being transparent? Or is there another issue with the logo?
