### ISSUE TITLE
Sort repo list and use github api

### ISSUE THREAD

**Issue by AntoineKM** [NationalSecurityAgency/nationalsecurityagency.github.io#49]
The repo list could be sorted from the most popular to the least popular because your best projects are not highlighted.

By the way I noticed that all `repos.json` were written manually which is clearly not ideal because the number of stars, forks, etc. are not updated, and if we used the GitHub api to solve this problem?

**Comment by ctubbsii** [comment]
GitHub's API would make the page slow to load. The JSON is updated periodically, but not frequently enough for my tastes to have the stargazers, forks, etc. counts be useful. But that is not my decision. In any case, closing this as duplicate issue of #40.
