### ISSUE TITLE
Absent URIs to Instagram and LinkedIn profiles in footer.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [NationalSecurityAgency/nationalsecurityagency.github.io#59]
The undermentioned:

1.	https://www.linkedin.com/company/national-security-agency/
1.	https://www.instagram.com/nsausgov/

...are absent from https://github.com/NationalSecurityAgency/nationalsecurityagency.github.io/blob/37fb2f2f702ade811766842e8bee532a360d60f6/_data/footer.yml#L48.

**Comment by csengineer1990** [comment]
Hi, I'm new here and would love to contribute. Could you please guide me on how I can assist with solving this issue, with your help?

**Comment by RokeJulianLockhart** [comment]
@csengineer1990, this is trivial to solve. It's a matter of absent Markdown markup. I seriously doubt you require guidance. Irrespective, why? You don't appear to be a constituent of the @NationalSecurityAgency.

**Comment by ctubbsii** [comment]
These cannot be added because they are not supported in the current site theme. This can be reconsidered if the theme is updated.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/NationalSecurityAgency/nationalsecurityagency.github.io/issues/59#issuecomment-2499040622

@ctubbsii, is that being tracked?

**Comment by ctubbsii** [comment]
> > [#59 (comment)](https://github.com/NationalSecurityAgency/nationalsecurityagency.github.io/issues/59#issuecomment-2499040622)
> 
> @ctubbsii, is that being tracked?

It is not something I am tracking, because the site works fine as is, so there is no need to spend time updating it. If somebody else wants to work on it, it would add to my workload to review it, so I'm not really pushing for that change right now. I'm fine with the current theme.
